#!/usr/bin/env python

from __future__ import print_function
import click
import itertools
import requests.exceptions
import logging
import json

import registry as registry_lib
import tablib
import tablib.formats
import tools.tablib_text_module

# add custom text output module of tablib
tablib.formats.available += (tools.tablib_text_module,)

# get all format titles
OUTPUT_FORMATS = map(lambda m: m.title, tablib.formats.available)

@click.group()
def cli():
    pass

def format(data, headers, format):
    if format == "text":
        for i in data:
            click.echo("- " + i[0])
    else:
        dataset = tablib.Dataset(headers=headers)
        map(dataset.append, data)
        click.echo(getattr(dataset, format))

def _list(generator, limit, output, insecure):
    try:
        if limit == 0:
            # list all
            items = [[n] for n in generator]
        else:
            items = [[n] for n in itertools.islice(generator, limit)]

        format(items, ["name"], output)
    except requests.exceptions.SSLError as e:
        logging.fatal(e.message)
        click.echo("Consider using --insecure")


@click.command()
@click.argument('REGISTRY')
@click.option('--limit', default=20, help='number of namespaces to show')
@click.option('--output', default='txt', type=click.Choice(OUTPUT_FORMATS))
@click.option('--insecure', default=False, is_flag=True)
def list(registry, limit, output, insecure):
    generator = registry_lib.API(registry, insecure=insecure).Catalog()
    _list(generator, limit, output, insecure)


@click.command()
@click.argument('IMAGE')
@click.option('--limit', default=20, help='number of tags to show')
@click.option('--output', default='txt', type=click.Choice(OUTPUT_FORMATS))
@click.option('--insecure', default=False, is_flag=True)
def tags(image, limit, output, insecure):
    ri = registry_lib.Image.from_image(image)

    generator = registry_lib.API(ri.registry, insecure=insecure).Tags(ri.repository)
    _list(generator, limit, output, insecure)


@click.command()
@click.argument('TYPE')
@click.argument('IMAGE')
@click.option('--output', default='txt', type=click.Choice(OUTPUT_FORMATS))
@click.option('--insecure', default=False, is_flag=True)
def inspect(type, image, output, insecure):
    ri = registry_lib.Image.from_image(image)

    manifest = registry_lib.API(ri.registry, insecure=insecure).Manifest(ri.repository, ri.reference).get().json()
    labels = json.loads(manifest['history'][0]['v1Compatibility'])['container_config']['Labels']
    labels_to_format = map(lambda k: [k,labels[k]], labels)
    format(labels_to_format, ["name", "value"], output)

cli.add_command(list)
cli.add_command(tags)
cli.add_command(inspect)


if __name__ == '__main__':
    cli()